language: java

jdk:

  - oraclejdk8

  - openjdk8

cache:

  directories:

    - '$HOME/.m2'

    - '$HOME/.sonar/cache'

dist: trusty
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - chmod +x mvnw
  
